[package]
name = "polkadot-primitives-test-helpers"
version = "0.9.23"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
sp-keyring = { git = "https://github.com/purestake/substrate", branch = "elois-background-sig-0.23.0" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/purestake/substrate", default-features = false , branch = "elois-background-sig-0.23.0" }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "elois-background-sig-0.23.0" }
polkadot-primitives = { path = "../" }
rand = "0.8.5"
